server.port=${SERVER_PORT:8081}

# PostgreSQL DB Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smartrent_audit}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:smartrent}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar integración con Azure AD
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.credential.client-id=749dc676-d557-460a-b138-dac9a6744b6e
spring.cloud.azure.active-directory.app-id-uri=api://749dc676-d557-460a-b138-dac9a6744b6e

# OAuth2 Resource Server JWT Validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://753ae9df-d5ec-4c6b-8227-b334fc775087.ciamlogin.com/753ae9df-d5ec-4c6b-8227-b334fc775087/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=749dc676-d557-460a-b138-dac9a6744b6e
