server.port=8080

# Habilitar integración con Azure AD
spring.cloud.azure.active-directory.enabled=true

# Client ID del registro del API en Entra ID
spring.cloud.azure.active-directory.credential.client-id=749dc676-d557-460a-b138-dac9a6744b6e

# application ID URI configurado en "Expose an API"
spring.cloud.azure.active-directory.app-id-uri=api://749dc676-d557-460a-b138-dac9a6744b6e

# OAuth2 Resource Server JWT Validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://753ae9df-d5ec-4c6b-8227-b334fc775087.ciamlogin.com/753ae9df-d5ec-4c6b-8227-b334fc775087/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=749dc676-d557-460a-b138-dac9a6744b6e
