version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smartrent-postgres
    environment:
      POSTGRES_USER: smartrent
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartrent_audit
    ports:
      - "5432:5432"
    networks:
      - smartrent-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  smartrent-catalog:
    build: ../ms-smartrent-catalog
    container_name: smartrent-catalog
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://smartrent-postgres:5432/smartrent_audit
    depends_on:
      - postgres
    networks:
      - smartrent-network

  smartrent-rentals:
    build: ../ms-smartrent-rentals
    container_name: smartrent-rentals
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://smartrent-postgres:5432/smartrent_audit
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_HOST}:9092
      - CATALOG_URL=http://smartrent-catalog:8081
    depends_on:
      - postgres
      - smartrent-catalog
    networks:
      - smartrent-network

  smartrent-notify:
    build: ../ms-smartrent-notify
    container_name: smartrent-notify
    environment:
      - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
    networks:
      - smartrent-network

  smartrent-audit:
    build: ../ms-smartrent-audit
    container_name: smartrent-audit
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://smartrent-postgres:5432/smartrent_audit
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_HOST}:9092
    depends_on:
      - postgres
    networks:
      - smartrent-network

  smartrent-report:
    build: ../ms-smartrent-report
    container_name: smartrent-report
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_HOST}:9092
    networks:
      - smartrent-network

  smartrent-bff:
    build: ../ms-smartrent-bff
    container_name: smartrent-bff
    ports:
      - "8080:8080"
    depends_on:
      - smartrent-catalog
      - smartrent-rentals
      - smartrent-report
      - smartrent-audit
    networks:
      - smartrent-network

volumes:
  pgdata:

networks:
  smartrent-network:
    name: smartrent-network
    driver: bridge
